# Generated by Django 3.0.8 on 2020-11-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_vehicle_is_open"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
                ("alt_text", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="vehicle",
            name="images",
            field=models.ManyToManyField(to="catalog.Image"),
        ),
    ]
