# Generated by Django 3.0.8 on 2020-11-20 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_auto_20201115_2237"),
    ]

    operations = [
        migrations.RemoveField(model_name="vehicle", name="images",),
        migrations.AddField(
            model_name="image",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.Vehicle",
            ),
        ),
    ]
