# Generated by Django 3.0.8 on 2020-11-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_auto_20201120_2046"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="alt_text",),
        migrations.AddField(
            model_name="image",
            name="is_primary",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.Vehicle",
            ),
        ),
    ]
