# Generated by Django 3.0.8 on 2020-12-18 20:20

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_auto_20201209_1949"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle", options={"ordering": ("created_at",)},
        ),
        migrations.RenameField(
            model_name="vehicle", old_name="name", new_name="title",
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to=catalog.models.Image.path_and_rename),
        ),
        migrations.AlterField(
            model_name="image",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.Vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.CharField(
                choices=[
                    ("--------", "Default"),
                    ("Audi", "Audi"),
                    ("BMW", "Bmw"),
                    ("Dodge", "Dodge"),
                    ("Fiat", "Fiat"),
                    ("Ford", "Ford"),
                    ("GMC", "Gmc"),
                    ("Honda", "Honda"),
                    ("Hyundai", "Hyundai"),
                    ("Infiniti", "Infiniti"),
                    ("Jaguar", "Jaguar"),
                    ("Jeep", "Jeep"),
                    ("Kia", "Kia"),
                    ("Land_Rover", "Land Rover"),
                    ("Lexus", "Lexus"),
                    ("Lincoln", "Lincoln"),
                    ("Lotus", "Lotus"),
                    ("Maserati", "Maserati"),
                    ("Mazda", "Mazda"),
                    ("Mercedes_Benz", "Mercedes Benz"),
                    ("Mitsubishi", "Mitsubishi"),
                    ("Nissan", "Nissan"),
                    ("Porsche", "Porsche"),
                    ("Rolls_Royce", "Rolls Royce"),
                    ("Smart", "Smart"),
                    ("Suzuki", "Suzuki"),
                    ("Tesla", "Tesla"),
                    ("Toyota", "Toyota"),
                    ("Volkswagen", "Volkswagen"),
                    ("Volvo", "Volvo"),
                ],
                default="--------",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="fuel",
            field=models.CharField(
                choices=[
                    ("--------", "Default"),
                    ("Petrol", "Petrol"),
                    ("Diesel", "Diesel"),
                    ("Electric", "Electric"),
                ],
                default="--------",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="location",
            field=models.CharField(
                choices=[("--------", "Default"), ("Benghazi", "Benghazi")],
                default="--------",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                choices=[
                    ("--------", "Default"),
                    ("Car", "Car"),
                    ("Motorbike", "Motorbike"),
                    ("Truck", "Truck"),
                ],
                default="--------",
                max_length=10,
            ),
        ),
    ]
